name: 'Slack Notify'
description: 'Send GitHub Action trigger data to Slack workflow'
inputs:
  message:
    description: 'Notification message'
    required: true
    type: string
  slack_webhook_url:
    description: 'Slack Webhook URL'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<@U24MN0951> GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Actions: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Author: <https://github.com/${{ github.actor }}|@${{ github.actor }}>"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        #SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
