name: 'Slack Notify'
description: 'Send GitHub Action trigger data to Slack workflow'
inputs:
  message:
    description: 'Notification message'
    required: true
    type: string
  slack_webhook_url:
    description: 'Slack Webhook URL'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}