name: 'Slack Notify'
description: 'Send GitHub Action trigger data to Slack workflow'
inputs:
  message:
    description: 'Notification message'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: |
          {
            "message": "${{ inputs.message }}",
            "author": "${{ github.event.sender.login }}",
            "repo_name": "${{ github.event.repository.full_name }}",
            "url": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "branch": "${{ github.ref }}",
            "status": "${{ job.status }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}

name: 'Slack Notify'
description: 'Send GitHub Action trigger data to Slack workflow'
inputs:
  message:
    description: 'Notification message'
    required: true
    type: string
  slack_webhook_url:
    description: 'Slack Webhook URL'
    required: true
    type: string
  color:
    description: 'Color of the message block'
    required: false
    type: string
    default: '#36a64f'
runs:
  using: 'composite'
  steps:
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "`${{ inputs.message }}`"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*Author:* `${{ github.event.sender.login }}`
                             *Repo:* `${{ github.event.repository.full_name }}`
                             *Branch:* `${{ github.ref }}`
                             *Status:* `${{ job.status }}`
                             *URL:* <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|Link>"
                  }
                ]
              }
            ],
            "attachments": [
              {
                "color": "${{ inputs.color }}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "`${{ inputs.message }}`"
                    }
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
