name: PROD Deploy using AWS CodeDeploy

on:
  pull_request:
    branches:
      - 'release'  
    types: [closed]
    
jobs:
  create-release:
    runs-on: ubuntu-latest
    if: "! startsWith(github.head_ref, 'revert-') && github.event.pull_request.merged == true"
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ### Todo: 余力があれば https://github.com/softprops/action-gh-release に切り替える
      ### actions/create-release repository が readonly となっている為 https://github.com/actions/create-release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.pull_request.title }}
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
          commitish: main

  deploy:
    name: Prod Deploy
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: ECS deploy
        run : |
          echo ${{ github.sha }}
          echo "DOCKER_IMAGE=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV
      
          ### イメージタグ
          # stg コンテナのタグを取得する
          STG_IMAGE_SHA=${{ github.event.pull_request.head.sha }}
          IMAGE_BRANCH="$(git name-rev --name-only HEAD | sed 's/\//_/g' | sed 's/\^/_/g')" >> $GITHUB_ENV
          PROD_IMAGE=$(cat VERSION)
          
          IMAGE_REV="$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_BRANCH}_${IMAGE_REV}" >> $GITHUB_ENV
          echo "STG_IMAGE_SHA:$STG_IMAGE_SHA"
          echo "DOCKER_IMAGE:$DOCKER_IMAGE"
          echo "IMAGE_REV:$IMAGE_REV"
          echo "IMAGE_BRANCH:$IMAGE_BRANCH"
          echo "IMAGE_TAG:$IMAGE_TAG"

  revert-deploy:
    name: PRD Deploy (revert)
    runs-on: ubuntu-latest
    if: "startsWith(github.head_ref, 'revert-') && github.event.pull_request.merged == true"
    permissions:
      id-token: write
      contents: read

    steps:
        - uses: actions/checkout@v4
    
        - name: ECS deploy
          run : |
            echo ${{ github.sha }}
            echo "DOCKER_IMAGE=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV
    
            ### イメージタグ
            IMAGE_BRANCH="$(git name-rev --name-only HEAD | sed 's/\//_/g' | sed 's/\^/_/g')" >> $GITHUB_ENV
            IMAGE_REV="$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            echo "IMAGE_TAG=${IMAGE_BRANCH}_${IMAGE_REV}" >> $GITHUB_ENV

            echo "DOCKER_IMAGE:$DOCKER_IMAGE"
            echo "IMAGE_REV:$IMAGE_REV"
            echo "IMAGE_BRANCH:$IMAGE_BRANCH"
            echo "IMAGE_TAG:$IMAGE_TAG"


