name: PROD Deploy using AWS CodeDeploy

on:
  pull_request:
    branches:
      - 'release'  
    types: [closed]
    
jobs:
  create-release:
    runs-on: ubuntu-latest
    if: "! startsWith(github.head_ref, 'revert-') && github.event.pull_request.merged == true"
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ### Todo: 余力があれば https://github.com/softprops/action-gh-release に切り替える
      ### actions/create-release repository が readonly となっている為 https://github.com/actions/create-release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.pull_request.title }}
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
          commitish: main

  deploy:
    name: Prod Deploy
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: ECS deploy
        run : |
          echo "Deploying Prod to ECS sample"
          echo "ecspresso deploy --config ecspresso.yml --region ap-northeast-1 --cluster my-cluster --service my-service --tag latest"
  
  revert-deploy:
    name: PRD Deploy (revert)
    runs-on: ubuntu-latest
    if: "startsWith(github.head_ref, 'revert-') && github.event.pull_request.merged == true"
    permissions:
      id-token: write
      contents: read

    steps:
        - uses: actions/checkout@v4
    
        - name: ECS deploy
          run : |
            echo "revert ECS deploy01"
